// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: washingmachine.proto

package com.matthewmurphy.smartwashingmachine;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.Empty)
    com.google.protobuf.MessageOrBuilder {
}
