// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: washingmachine.proto

package com.matthewmurphy.smartwashingmachine;

public final class SmartKitchenWashingmachineImpl {
  private SmartKitchenWashingmachineImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_statusOfSwitches_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_statusOfSwitches_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_statusOfDoor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_statusOfDoor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_washResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_washResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_washRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_washRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024washingmachine.proto\022\014smartkitchen\";\n\020" +
      "statusOfSwitches\022\024\n\014switchStatus\030\001 \001(\010\022\021" +
      "\n\tstatusMsg\030\002 \001(\t\":\n\014statusOfDoor\022\021\n\tope" +
      "nONOff\030\001 \001(\010\022\027\n\017statusOfDoorMsg\030\002 \001(\t\"/\n" +
      "\014washResponse\022\014\n\004wash\030\001 \001(\005\022\021\n\tstatusMsg" +
      "\030\002 \001(\t\".\n\013washRequest\022\014\n\004wash\030\001 \001(\005\022\021\n\ts" +
      "tatusMsg\030\002 \001(\t\"\007\n\005Empty2\362\002\n\016washingMachi" +
      "ne\022A\n\010switchOn\022\023.smartkitchen.Empty\032\036.sm" +
      "artkitchen.statusOfSwitches\"\000\022B\n\tswitchO" +
      "ff\022\023.smartkitchen.Empty\032\036.smartkitchen.s" +
      "tatusOfSwitches\"\000\022D\n\010doorOpen\022\032.smartkit" +
      "chen.statusOfDoor\032\032.smartkitchen.statusO" +
      "fDoor\"\000\022F\n\ndoorClosed\022\032.smartkitchen.sta" +
      "tusOfDoor\032\032.smartkitchen.statusOfDoor\"\000\022" +
      "K\n\016changeWashType\022\031.smartkitchen.washReq" +
      "uest\032\032.smartkitchen.washResponse\"\0000\001BI\n%" +
      "com.matthewmurphy.smartwashingmachineB\036S" +
      "martKitchenWashingmachineImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartkitchen_statusOfSwitches_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartkitchen_statusOfSwitches_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_statusOfSwitches_descriptor,
        new java.lang.String[] { "SwitchStatus", "StatusMsg", });
    internal_static_smartkitchen_statusOfDoor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartkitchen_statusOfDoor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_statusOfDoor_descriptor,
        new java.lang.String[] { "OpenONOff", "StatusOfDoorMsg", });
    internal_static_smartkitchen_washResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartkitchen_washResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_washResponse_descriptor,
        new java.lang.String[] { "Wash", "StatusMsg", });
    internal_static_smartkitchen_washRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartkitchen_washRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_washRequest_descriptor,
        new java.lang.String[] { "Wash", "StatusMsg", });
    internal_static_smartkitchen_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartkitchen_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
