// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: washingmachine.proto

package com.matthewmurphy.smartwashingmachine;

public interface statusOfSwitchesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.statusOfSwitches)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switchStatus = 1;</code>
   */
  boolean getSwitchStatus();
}
