// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: washingmachine.proto

package com.matthewmurphy.smartwashingmachine;

public interface statusOfDoorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.statusOfDoor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool openONOff = 1;</code>
   */
  boolean getOpenONOff();

  /**
   * <code>string statusOfDoorMsg = 2;</code>
   */
  java.lang.String getStatusOfDoorMsg();
  /**
   * <code>string statusOfDoorMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusOfDoorMsgBytes();
}
