// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: washingmachine.proto

package com.matthewmurphy.smartwashingmachine;

public interface washRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.washRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 wash = 1;</code>
   */
  int getWash();
}
