// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: washingmachine.proto

package com.matthewmurphy.smartwashingmachine;

public interface washResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.washResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 wash = 1;</code>
   */
  int getWash();

  /**
   * <code>string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
