// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cooker.proto

package com.matthewmurphy.smartcooker;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.Empty)
    com.google.protobuf.MessageOrBuilder {
}
