// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cooker.proto

package com.matthewmurphy.smartcooker;

public interface heatingStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.heatingStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool heatingONOFF = 1;</code>
   */
  boolean getHeatingONOFF();
}
