// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cooker.proto

package com.matthewmurphy.smartcooker;

public final class SmartKitchenCookerImpl {
  private SmartKitchenCookerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_statusOfSwitches_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_statusOfSwitches_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_heatingStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_heatingStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartkitchen_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartkitchen_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014cooker.proto\022\014smartkitchen\"(\n\020statusOf" +
      "Switches\022\024\n\014switchStatus\030\001 \001(\010\"%\n\rheatin" +
      "gStatus\022\024\n\014heatingONOFF\030\001 \001(\010\"\007\n\005Empty2\227" +
      "\002\n\013smartCooker\022A\n\010switchOn\022\023.smartkitche" +
      "n.Empty\032\036.smartkitchen.statusOfSwitches\"" +
      "\000\022B\n\tswitchOff\022\023.smartkitchen.Empty\032\036.sm" +
      "artkitchen.statusOfSwitches\"\000\022?\n\theating" +
      "On\022\023.smartkitchen.Empty\032\033.smartkitchen.h" +
      "eatingStatus\"\000\022@\n\nheatingOff\022\023.smartkitc" +
      "hen.Empty\032\033.smartkitchen.heatingStatus\"\000" +
      "B9\n\035com.matthewmurphy.smartcookerB\026Smart" +
      "KitchenCookerImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartkitchen_statusOfSwitches_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartkitchen_statusOfSwitches_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_statusOfSwitches_descriptor,
        new java.lang.String[] { "SwitchStatus", });
    internal_static_smartkitchen_heatingStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartkitchen_heatingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_heatingStatus_descriptor,
        new java.lang.String[] { "HeatingONOFF", });
    internal_static_smartkitchen_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartkitchen_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartkitchen_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
