// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cooker.proto

package com.matthewmurphy.smartcooker;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switchONOff = 1;</code>
   */
  boolean getSwitchONOff();

  /**
   * <code>string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
