// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fridge.proto

package com.matthewmurphy.smartfridge;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.Empty)
    com.google.protobuf.MessageOrBuilder {
}
