// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fridge.proto

package com.matthewmurphy.smartfridge;

public interface itemsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.itemsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string items = 1;</code>
   */
  java.lang.String getItems();
  /**
   * <code>string items = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemsBytes();
}
