// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fridge.proto

package com.matthewmurphy.smartfridge;

public interface numResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.numResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string items = 1;</code>
   */
  java.lang.String getItems();
  /**
   * <code>string items = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemsBytes();

  /**
   * <code>string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
