// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fridge.proto

package com.matthewmurphy.smartfridge;

public interface statusOfSwitchesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.statusOfSwitches)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switchStatus = 1;</code>
   */
  boolean getSwitchStatus();

  /**
   * <code>string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();
}
