// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fridge.proto

package com.matthewmurphy.smartfridge;

public interface statusOfDoorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartkitchen.statusOfDoor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>string statusOfDoorMsg = 2;</code>
   */
  java.lang.String getStatusOfDoorMsg();
  /**
   * <code>string statusOfDoorMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusOfDoorMsgBytes();
}
